### PR TITLE
Remove Grunt for Gulp, Update Angular to 1.6.4

### PR DESCRIPTION
**Pull request by jdonisvitch**
Updated angular/bower packages
Updated all NPM packages except gulp-filter
Updated Router to work with 1.6.4
Removed Grunt for Gulp

### CODE REVIEW

**Comment by jdonisvitch** [comment]
Only WIP -- figuring out how isolatedScope changed while testing.. Perhaps it is actually broken else where in code-- probably not tho.. I have a hunch it's only testing for isolatedScope.

**Comment by jdonisvitch** [comment]
@maxatbrs -- fuxlered this up

**Comment by jdonisvitch** [comment]
https://code.angularjs.org/1.6.4/docs/api/ng/provider/$compileProvider << possibly helpful for directives and testing directives 

https://github.com/angular/angular.js/blob/master/CHANGELOG.md

^^ There are some bug fixes and new fundamentals that we need to figure out in this changelog. Specifically the 25 out of 50 tests failing due to either bug fixes, or better practices from new functionality.

**Comment by maxfelker** [comment]
Nice looking good so far. Is this merge ready or does it still need love?

**Comment by jdonisvitch** [comment]
@maxatbrs -- I need to test the assumption that only the part of the tests are broken. Also, it'd be good to fix those tests in the event that it is just that failing.

**Comment by jdonisvitch** [comment]
There is busted functionality here - which is reflected in the tests. Mostly having to do with isolateScope and the CRUD piece. @maxatbrs -- you said you were gonna refactor this stuff anyhow ?

**Comment by maxfelker** [comment]
Okay updated this and fixed conflicts. Found that there are 15 errors in the tests which I'm going to look into, seems like it is isolated scope stuff.

```javascript
PhantomJS 2.1.1 (Mac OS X 0.0.0) The Users Management Controller When the controller loads When the user opens the create form when the user updates an User should call the Create Crud Base Method which calls the Crud Service FAILED
	forEach@bower_components/angular/angular.js:403:24
	loadModules@bower_components/angular/angular.js:4880:12
	createInjector@bower_components/angular/angular.js:4802:30
	WorkFn@bower_components/angular-mocks/angular-mocks.js:3163:60
	bower_components/angular/angular.js:4921:53
	TypeError: undefined is not a constructor (evaluating 'controller('UsersCtrl', {
	      $scope: scope
	    })') in test/spec/controllers/users.js (line 40)
	initController@test/spec/controllers/users.js:40:27
	test/spec/controllers/users.js:55:21
	Error: spyOn could not find an object to spy upon for updateUser() in node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 1984)
	test/spec/controllers/users.js:104:16
	TypeError: undefined is not an object (evaluating 'UsersCtrl.updateUser') in test/spec/controllers/users.js (line 112)
	test/spec/controllers/users.js:112:20
```

**Comment by maxfelker** [comment]
Issues with code, need to migrate with this guide below. I'll rage this.

https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6

screen shot 2017-04-17 at 9 52 51 am

**Comment by maxfelker** [comment]
The issue was not with how our code was setup but how our test harness was setup to compile and apply data into specific scopes. After refactoring some of the tests, specifically in the beforeEach blocks, I was able to persist the tests and make them better.

**Pull request merged**
